[package]
name = "vmlord-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vmlord-core = { path = "../core" }
log.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_Vhd",
    "Win32_System_HostComputeNetwork",
    "Win32_System_HostComputeSystem",
    "Win32_System_IO",
    "Win32_System_Threading",
] }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
