use std::{fs::{self, File}, io::{self, Write}, path::{Path, PathBuf}, sync::atomic::{AtomicBool, Ordering}};
use crate::{PayloadError, PayloadProgress, ReadyGpuPayload, ReadyMarker, Sha256Digest};

pub struct StagedGpuPayload { payload_id: String, generation: Sha256Digest, generation_directory: PathBuf, ready_marker_path: PathBuf }
impl StagedGpuPayload { pub fn payload_id(&self)->&str{&self.payload_id} pub fn generation(&self)->&Sha256Digest{&self.generation} pub fn generation_directory(&self)->&Path{&self.generation_directory} pub fn ready_marker_path(&self)->&Path{&self.ready_marker_path} }
pub fn ensure_staging_root(path:&Path)->Result<(),PayloadError>{ for child in ["generations","ready"] { let directory=path.join(child); fs::create_dir_all(&directory).map_err(|e|PayloadError::io("create GPU payload staging directory",directory,e))?; } Ok(()) }
pub fn stage_payload(payload:&ReadyGpuPayload,root:&Path,progress:&dyn Fn(PayloadProgress),cancel:&AtomicBool)->Result<StagedGpuPayload,PayloadError>{ stage_with(payload,root,&|source,target|fs::hard_link(source,target),progress,cancel) }
pub(crate) fn stage_with(payload:&ReadyGpuPayload,root:&Path,hard_link:&dyn Fn(&Path,&Path)->io::Result<()>,progress:&dyn Fn(PayloadProgress),cancel:&AtomicBool)->Result<StagedGpuPayload,PayloadError>{
 ensure_staging_root(root)?; let digest=payload.generation().as_hex(); let generation=root.join("generations").join(digest); let marker=root.join("ready").join(format!("{digest}.json"));
 if !generation.exists() { let temp=root.join("generations").join(format!(".tmp-{digest}-{}",std::process::id())); fs::create_dir_all(&temp).map_err(|e|PayloadError::io("create staging temporary directory",temp.clone(),e))?; let mut files=vec!["payload.json".to_owned()]; files.extend(payload.manifest().files().iter().map(|file|file.path().to_owned())); for (index,relative) in files.iter().enumerate() { if cancel.load(Ordering::Relaxed){return Err(PayloadError::Cancelled)} let source=payload.files_directory().join(relative); let target=temp.join(relative); if let Some(parent)=target.parent(){fs::create_dir_all(parent).map_err(|e|PayloadError::io("create staging subdirectory",parent.into(),e))?;} if hard_link(&source,&target).is_err(){ fs::copy(&source,&target).map_err(|e|PayloadError::io("copy GPU payload staging file",target.clone(),e))?; } progress(PayloadProgress::Staging{files:(index+1)as u64,total:files.len()as u64}); } match fs::rename(&temp,&generation){ Ok(())=>(), Err(_error) if generation.exists()=>{let _=fs::remove_dir_all(&temp);}, Err(error)=>return Err(PayloadError::io("publish GPU payload generation",generation.clone(),error)), } }
 if !marker.exists() { let partial=root.join("ready").join(format!(".{digest}.part-{}",std::process::id())); let mut file=File::options().write(true).create_new(true).open(&partial).map_err(|e|PayloadError::io("create ready marker",partial.clone(),e))?; file.write_all(&ReadyMarker::new_for(payload).to_json_bytes()?).map_err(|e|PayloadError::io("write ready marker",partial.clone(),e))?; file.sync_all().map_err(|e|PayloadError::io("flush ready marker",partial.clone(),e))?; match fs::rename(&partial,&marker){ Ok(())=>(), Err(_error) if marker.exists()=>{let _=fs::remove_file(&partial);}, Err(error)=>return Err(PayloadError::io("publish ready marker",marker.clone(),error)), } }
 progress(PayloadProgress::Ready); Ok(StagedGpuPayload{payload_id:payload.payload_id().into(),generation:payload.generation().clone(),generation_directory:generation,ready_marker_path:marker})
}
