[package]
name = "vmlord"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "vmlord"
test = false
bench = false

[dependencies]
log.workspace = true
vmlord-app = { path = "../app" }
vmlord-core = { path = "../core" }
vmlord-legacy-backend = { path = "../legacy-backend" }
vmlord-platform = { path = "../platform" }
vmlord-ui = { path = "../ui" }

[build-dependencies]
embed-resource = "3.0"

[lints]
workspace = true
