//! Proving that the agent on the other end of a session holds the VM's secret.
//!
//! One secret per VM, minted when the VM is created and handed to the guest
//! through the same provisioning medium that carries its password hash and its
//! authorized key. It never travels on this protocol: what crosses the wire is
//! a nonce the verifier made up for this session and an HMAC-SHA-256 tag over
//! it, which proves the secret is held without saying anything about it.
//!
//! The nonce is fresh per session and is what makes a captured tag worthless
//! later. Nothing here rotates the secret: a VM's secret lives as long as the
//! VM does, and replacing one means recreating the guest that reads it.

use std::{error::Error, fmt};

use base64::{Engine, engine::general_purpose::STANDARD};
use hmac::{Hmac, KeyInit, Mac};
use sha2::Sha256;
use subtle::ConstantTimeEq;
use zeroize::Zeroizing;

use crate::v1::request;

/// The length of a secret, a nonce and a tag alike, in bytes.
///
/// Thirty-two because that is HMAC-SHA-256's output width, and a key shorter
/// than the hash's block would only weaken the tag while a longer one would be
/// hashed down to this anyway.
pub const LEN: usize = 32;

/// Where the secret waits for the agent inside the guest.
///
/// Named here rather than in either of the two crates that use it: the host
/// writes this file through the VM's provisioning medium and the agent reads
/// it, and a path the two spelled separately is a path they could spell
/// differently. Under `/etc` because it is configuration that must survive a
/// reboot, and readable by root alone -- anything that can read it can open a
/// session as this VM's agent.
pub const GUEST_SECRET_PATH: &str = "/etc/vmlord/agent.secret";

/// What the tag is computed over, ahead of the nonce.
///
/// Domain separation, so that a tag made here can never be mistaken for -- or
/// replayed as -- a MAC some later feature computes with the same secret. It
/// names the protocol version too: a future major that changes what
/// authentication means gets its own string rather than inheriting this one.
const DOMAIN: &[u8] = b"vmlord.agent.v1.auth";

/// A VM's shared secret, held by the host and by the agent in that VM.
///
/// No `Debug` and no `Display`, by design: the one thing this type must never
/// do is print itself. `VmKeyPair` in `vmlord-keys` protects the private half
/// of an SSH key the same way.
pub struct Secret(Zeroizing<[u8; LEN]>);

impl Secret {
    /// Mints a secret from the operating system's random source.
    #[must_use]
    pub fn generate() -> Self {
        Self(Zeroizing::new(random()))
    }

    /// Reads a secret back from the form it is stored and delivered in.
    ///
    /// Surrounding whitespace is ignored, because the file this comes out of
    /// is a text file and both ends of it may have been written by something
    /// that ends lines.
    ///
    /// # Errors
    ///
    /// [`SecretError`] if the text is not base64 or does not decode to exactly
    /// [`LEN`] bytes. Both mean the secret was truncated or is not one at all,
    /// and neither is something to recover from by padding.
    pub fn from_base64(text: &str) -> Result<Self, SecretError> {
        let bytes = Zeroizing::new(STANDARD.decode(text.trim()).map_err(|_| SecretError)?);
        let bytes: [u8; LEN] = bytes.as_slice().try_into().map_err(|_| SecretError)?;

        Ok(Self(Zeroizing::new(bytes)))
    }

    /// The secret as base64, which is how it is written to a file and handed
    /// to the guest.
    ///
    /// `Zeroizing` because the returned `String` is as much the secret as the
    /// bytes behind it, and a caller that drops it should not leave a copy in
    /// the allocator.
    #[must_use]
    pub fn to_base64(&self) -> Zeroizing<String> {
        Zeroizing::new(STANDARD.encode(self.0.as_slice()))
    }
}

/// The challenge one session's authentication is built on.
///
/// Generated by the verifier -- the host -- once per session, so that a tag is
/// good for that session and no other.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Nonce([u8; LEN]);

impl Nonce {
    /// Draws a fresh nonce from the operating system's random source.
    #[must_use]
    pub fn generate() -> Self {
        Self(random())
    }

    /// The bytes to put in the challenge message.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; LEN] {
        &self.0
    }

    /// Reads a nonce out of a challenge that arrived on the wire.
    ///
    /// # Errors
    ///
    /// [`WrongLength`] if the peer sent anything other than [`LEN`] bytes. A
    /// short nonce is a weak challenge, so it is refused rather than accepted
    /// and padded out.
    pub fn from_wire(bytes: &[u8]) -> Result<Self, WrongLength> {
        Ok(Self(bytes.try_into().map_err(|_| WrongLength {
            what: "nonce",
            len: bytes.len(),
        })?))
    }
}

/// The proof that the peer holds the secret a nonce was sent to.
///
/// A tag says nothing about the secret and is worthless once its session is
/// over, so unlike [`Secret`] it may be compared, copied and printed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Tag([u8; LEN]);

impl Tag {
    /// The bytes to put in the answer message.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; LEN] {
        &self.0
    }

    /// Reads a tag out of an answer that arrived on the wire.
    ///
    /// # Errors
    ///
    /// [`WrongLength`] if the peer sent anything other than [`LEN`] bytes.
    pub fn from_wire(bytes: &[u8]) -> Result<Self, WrongLength> {
        Ok(Self(bytes.try_into().map_err(|_| WrongLength {
            what: "tag",
            len: bytes.len(),
        })?))
    }
}

/// Answers `nonce` with the tag `secret` produces for it.
///
/// This is the guest's half of the exchange, and also how the host works out
/// what it expects to receive: one function, so that the two sides cannot
/// disagree about what is being signed.
#[must_use]
pub fn tag(secret: &Secret, nonce: &Nonce) -> Tag {
    let mut mac = Hmac::<Sha256>::new_from_slice(secret.0.as_slice())
        .expect("HMAC accepts a key of any length");
    mac.update(DOMAIN);
    mac.update(nonce.as_bytes());

    Tag(mac.finalize().into_bytes().into())
}

/// Whether `answer` is the tag `secret` produces for `nonce`.
///
/// The comparison is constant-time: an early return on the first differing
/// byte would let a peer that does not hold the secret find one byte at a
/// time how far it got.
#[must_use]
pub fn verify(secret: &Secret, nonce: &Nonce, answer: &Tag) -> bool {
    tag(secret, nonce).0.ct_eq(&answer.0).into()
}

/// Whether a request may be served before the session has authenticated.
///
/// Only the two that get a session to that point: the hello that settles the
/// version, and the answer to the challenge itself. Everything else is
/// refused with [`ErrorCode::Unauthenticated`](crate::v1::ErrorCode::Unauthenticated)
/// until the tag has been verified.
///
/// The rule lives beside the exchange rather than in the transport that runs
/// it: what a session may do before it has proved anything is part of the
/// protocol, and the host and any later transport must not each decide it.
#[must_use]
pub fn allowed_unauthenticated(kind: &request::Kind) -> bool {
    matches!(
        kind,
        request::Kind::Hello(_) | request::Kind::Authenticate(_)
    )
}

/// Text that is not a secret.
///
/// Carries nothing about what was wrong beyond that: the input is the secret
/// itself, and an error that quoted it would put it in a log.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SecretError;

impl fmt::Display for SecretError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "the agent secret is not {LEN} base64-encoded bytes"
        )
    }
}

impl Error for SecretError {}

/// A nonce or a tag that arrived with the wrong number of bytes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WrongLength {
    /// Which of the two it was, for the message.
    what: &'static str,
    /// How many bytes the peer sent.
    len: usize,
}

impl fmt::Display for WrongLength {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "the peer sent a {}-byte {}, and this protocol's is {LEN} bytes",
            self.len, self.what
        )
    }
}

impl Error for WrongLength {}

/// Fills an array from the operating system's random source.
///
/// A failure here is not something a caller could handle: it means the system
/// has no entropy source, and everything else this crate does with a secret
/// would be unsound. `getrandom` rather than a generator of our own, because
/// the host and the guest then both draw from what their kernel offers.
fn random() -> [u8; LEN] {
    let mut bytes = [0u8; LEN];
    getrandom::fill(&mut bytes).expect("the operating system has a random source");
    bytes
}

#[cfg(test)]
mod tests {
    use base64::{Engine, engine::general_purpose::STANDARD};

    use crate::{
        auth::{LEN, Nonce, Secret, Tag, allowed_unauthenticated, tag, verify},
        frame,
        v1::{
            AuthenticateRequest, AuthenticateResponse, Envelope, HeartbeatRequest, HelloRequest,
            Request, Response, envelope, request, response,
        },
    };

    #[test]
    fn both_peers_holding_the_secret_compute_the_same_tag() {
        let secret = Secret::generate();
        let nonce = Nonce::generate();

        assert!(verify(&secret, &nonce, &tag(&secret, &nonce)));
    }

    #[test]
    fn a_tag_from_another_secret_is_refused() {
        let nonce = Nonce::generate();
        let forged = tag(&Secret::generate(), &nonce);

        assert!(!verify(&Secret::generate(), &nonce, &forged));
    }

    #[test]
    fn an_answer_to_another_session_is_refused() {
        // What a peer that recorded an earlier session would replay.
        let secret = Secret::generate();
        let recorded = tag(&secret, &Nonce::generate());

        assert!(!verify(&secret, &Nonce::generate(), &recorded));
    }

    #[test]
    fn every_session_gets_a_nonce_of_its_own() {
        assert_ne!(Nonce::generate(), Nonce::generate());
    }

    #[test]
    fn a_secret_survives_the_form_it_is_stored_in() {
        let secret = Secret::generate();
        let nonce = Nonce::generate();
        let stored = secret.to_base64();

        let read_back = Secret::from_base64(&stored).expect("what was just written");

        assert!(verify(&read_back, &nonce, &tag(&secret, &nonce)));
    }

    #[test]
    fn a_stored_secret_of_the_wrong_size_is_not_read_as_one() {
        for text in ["", "not base64!", &STANDARD.encode([7u8; LEN - 1])] {
            assert!(
                Secret::from_base64(text).is_err(),
                "\"{text}\" must not be read as a secret"
            );
        }
    }

    #[test]
    fn a_stored_secret_is_read_back_through_the_whitespace_a_file_ends_with() {
        let secret = Secret::generate();
        let nonce = Nonce::generate();
        let stored = format!("{}\n", secret.to_base64().as_str());

        let read_back = Secret::from_base64(&stored).expect("a secret with a trailing newline");

        assert!(verify(&read_back, &nonce, &tag(&secret, &nonce)));
    }

    #[test]
    fn a_nonce_and_a_tag_survive_the_wire() {
        let secret = Secret::generate();
        let nonce = Nonce::generate();
        let answer = tag(&secret, &nonce);

        let nonce = Nonce::from_wire(nonce.as_bytes()).expect("a nonce of the right length");
        let answer = Tag::from_wire(answer.as_bytes()).expect("a tag of the right length");

        assert!(verify(&secret, &nonce, &answer));
    }

    /// The exchange as the two peers actually run it: the host asks with a
    /// nonce, the agent answers with a tag over it, and both messages survive
    /// the framing they travel in.
    #[test]
    fn a_challenge_and_its_answer_survive_the_framing() {
        let secret = Secret::generate();
        let nonce = Nonce::generate();

        let challenge = Envelope::request(
            1,
            request::Kind::Authenticate(AuthenticateRequest {
                nonce: nonce.as_bytes().to_vec(),
            }),
        );
        let challenge = round_trip(&challenge);
        let Some(envelope::Body::Request(Request {
            kind: Some(request::Kind::Authenticate(challenge)),
        })) = challenge.body
        else {
            panic!("expected an authenticate request");
        };
        let nonce = Nonce::from_wire(&challenge.nonce).expect("the nonce the host sent");

        let answer = Envelope::response(
            1,
            response::Kind::Authenticate(AuthenticateResponse {
                tag: tag(&secret, &nonce).as_bytes().to_vec(),
            }),
        );
        let answer = round_trip(&answer);
        let Some(envelope::Body::Response(Response {
            kind: Some(response::Kind::Authenticate(answer)),
        })) = answer.body
        else {
            panic!("expected an authenticate response");
        };

        let answer = Tag::from_wire(&answer.tag).expect("the tag the agent sent");
        assert!(verify(&secret, &nonce, &answer));
    }

    #[test]
    fn opening_a_session_is_all_an_unauthenticated_peer_may_do() {
        assert!(allowed_unauthenticated(&request::Kind::Hello(
            HelloRequest::default()
        )));
        assert!(allowed_unauthenticated(&request::Kind::Authenticate(
            AuthenticateRequest::default()
        )));
    }

    #[test]
    fn everything_else_waits_until_the_session_is_authenticated() {
        assert!(!allowed_unauthenticated(&request::Kind::Heartbeat(
            HeartbeatRequest {}
        )));
    }

    /// Writes `envelope` as a frame and reads it back, so that a test asserts
    /// on what the peer would receive rather than on the value it built.
    fn round_trip(envelope: &Envelope) -> Envelope {
        let mut buffer = Vec::new();
        let mut stream = Vec::new();
        frame::write(&mut stream, envelope, &mut buffer).expect("a writable stream");

        frame::read(&mut stream.as_slice(), &mut buffer).expect("the frame just written")
    }

    #[test]
    fn a_nonce_or_a_tag_of_the_wrong_length_is_refused() {
        for len in [0, LEN - 1, LEN + 1] {
            let bytes = vec![0u8; len];

            assert!(
                Nonce::from_wire(&bytes).is_err(),
                "a {len}-byte nonce must be refused"
            );
            assert!(
                Tag::from_wire(&bytes).is_err(),
                "a {len}-byte tag must be refused"
            );
        }
    }
}
